# /home/siisi/property-management/prod/docker-compose.yml

services:
  # --- Database ---
  db:
    image: postgres:latest
    container_name: manager_prod-db
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - manager_prod-db-data:/var/lib/postgresql/data/pgdata
      - ./odoo_pg_pass:/run/secrets/postgresql_password:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 15s
      timeout: 15s
      retries: 15
    restart: always

  # --- Odoo Services ---
  manager_prod:
    build: .
    container_name: manager_prod
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ADDONS_PATH=/mnt/custom-addons,/usr/lib/python3/site-packages/odoo/addons
      - PROXY_MODE=True
    ports:
      - "8011:8069"
    volumes:
      - manager_prod-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/custom-addons
      - ./logs:/var/log/odoo
    secrets:
      - postgresql_password
    restart: always

volumes:
  manager_prod-db-data:
  manager_prod-data:

secrets:
  postgresql_password:
    file: odoo_pg_pass
